
services:
  mongodb:
    image: mongo:latest
    container_name: virtual-pet-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: virtualpet
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: